export const WORKSPACE_GIT_DIFF_PATHSPEC_ARGS = "-- . ':(exclude).loom'";
export const WORKSPACE_GIT_DIFF_STAT_COMMAND = `git diff --stat ${WORKSPACE_GIT_DIFF_PATHSPEC_ARGS}`;
export const WORKSPACE_GIT_DIFF_PATCH_COMMAND = `git diff ${WORKSPACE_GIT_DIFF_PATHSPEC_ARGS}`;
export const WORKSPACE_GIT_DIFF_COMMAND = `${WORKSPACE_GIT_DIFF_STAT_COMMAND} && ${WORKSPACE_GIT_DIFF_PATCH_COMMAND}`;
